// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/input/programming_lang_input.go

// Package mock_input is a generated GoMock package.
package mock_input

import (
	context "context"
	model "github.com/SekiguchiKai/clean-architecture-with-go/server/domain/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockProgrammingLangInputPort is a mock of ProgrammingLangInputPort interface
type MockProgrammingLangInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockProgrammingLangInputPortMockRecorder
}

// MockProgrammingLangInputPortMockRecorder is the mock recorder for MockProgrammingLangInputPort
type MockProgrammingLangInputPortMockRecorder struct {
	mock *MockProgrammingLangInputPort
}

// NewMockProgrammingLangInputPort creates a new mock instance
func NewMockProgrammingLangInputPort(ctrl *gomock.Controller) *MockProgrammingLangInputPort {
	mock := &MockProgrammingLangInputPort{ctrl: ctrl}
	mock.recorder = &MockProgrammingLangInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockProgrammingLangInputPort) EXPECT() *MockProgrammingLangInputPortMockRecorder {
	return m.recorder
}

// List mocks base method
func (m *MockProgrammingLangInputPort) List(ctx context.Context, limit int) ([]*model.ProgrammingLang, error) {
	ret := m.ctrl.Call(m, "List", ctx, limit)
	ret0, _ := ret[0].([]*model.ProgrammingLang)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockProgrammingLangInputPortMockRecorder) List(ctx, limit interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProgrammingLangInputPort)(nil).List), ctx, limit)
}

// Get mocks base method
func (m *MockProgrammingLangInputPort) Get(ctx context.Context, id int) (*model.ProgrammingLang, error) {
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*model.ProgrammingLang)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockProgrammingLangInputPortMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProgrammingLangInputPort)(nil).Get), ctx, id)
}

// Create mocks base method
func (m *MockProgrammingLangInputPort) Create(ctx context.Context, param *model.ProgrammingLang) (*model.ProgrammingLang, error) {
	ret := m.ctrl.Call(m, "Create", ctx, param)
	ret0, _ := ret[0].(*model.ProgrammingLang)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockProgrammingLangInputPortMockRecorder) Create(ctx, param interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProgrammingLangInputPort)(nil).Create), ctx, param)
}

// Update mocks base method
func (m *MockProgrammingLangInputPort) Update(ctx context.Context, id int, param *model.ProgrammingLang) (*model.ProgrammingLang, error) {
	ret := m.ctrl.Call(m, "Update", ctx, id, param)
	ret0, _ := ret[0].(*model.ProgrammingLang)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update
func (mr *MockProgrammingLangInputPortMockRecorder) Update(ctx, id, param interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProgrammingLangInputPort)(nil).Update), ctx, id, param)
}

// Delete mocks base method
func (m *MockProgrammingLangInputPort) Delete(ctx context.Context, id int) error {
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockProgrammingLangInputPortMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProgrammingLangInputPort)(nil).Delete), ctx, id)
}
